# Numpy

We will be learning about some basic programming and data analysis using Numpy and Pandas. First up - NumPy

NumPy is the fundamental package for scientific computing in Python. It is used across many fields inc. Mathematics, Engineering, Finance, Data Science, Artificial Intelligence, Machine Learning etc. Most scientific computing libraries will build on NumPy.

Numpy provides functions to work with N-dimensional arrays and an assortment of routines for fast operations on such arrays: matrix mathematics, logical, shape manipulation, statistical operations, random simulation etc.

## Basic Numpy tools

<img src="https://matteding.github.io/images/broadcasting-3d-scalar.gif" width="400" height="400" align="left"/>


Here, we will exam some fairly simple tools in Numpy for the management of data and doing basic statistics. First, lets make sure numpy is imported:


In [ ]:
import numpy as np

### Array creation and Indexing

In the cells below we will learn basic array creation and indexing


In [ ]:
a = np.array([1, 2, 3])            # Create a simple array
print("Numpy Array 'a':\n")
print(type(a))                     # Prints type as recognised by Python
print(a.shape)                     # Prints its shape
print(a[0], a[1], a[2])            # Prints certain indexed values
a[0] = 5                           # Change an element of the array
print(a,"\n")                   


print("Numpy Array 'b':\n")
b = np.array([[1,2,3],[4,5,6]])    # Create an array with more 'complexity'
print(b.shape)
print(b)                     
print(b[0, 0], b[0, 1], b[1, 0])  


Numpy Array 'a':

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3] 

Numpy Array 'b':

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


### Array manipulation and mathematics
Where numpy gets really powerful is its efficiency in array manipulation and mathematics.

In [ ]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y,'\n')
print(x * y,'\n') 

# numpy has many mathematical functions built in - accessed via dot notation
print(np.sqrt(x),'\n')
print(np.dot(x, y),'\n')
print(np.cross(x, y),'\n')

[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[19 22]
 [43 50]] 

[-4 -4] 



C:\Users\hecto\AppData\Local\Temp\ipykernel_3508\15743206.py:10: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x, y),'\n')


Numpy also provides aggregation methods.

In [ ]:
print(x.sum())  # sum over the entire matrix
print(y.mean(axis=1))  # mean of each row

10
[5.5 7.5]


## Activity
Your turn... <br>
Add comments that explain what your code is doing

#### 1) Create the following 3 x 4 array and call it 'c'

[[ 1  2  3  4] <br>
 [ 5  6  7  8] <br>
 [ 9 10 11 12]] <br>

In [ ]:
# Create the following 3 x 4 array and call it 'c':
c = np.array([[1, 2,3,4], [5,6,7,8],[9, 10, 11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 2) Print all values in rows 2 & 3

In [ ]:
# Print all values in rows 2 & 3
print(c[1,:])
print(c[2,:])

[5 6 7 8]
[ 9 10 11 12]


#### 3) Print the values in the 2nd row and in cols 1 & 3

In [ ]:
# Print the values in the 2nd row and in cols 1 & 3
print(c[1,[0,2]])

[5 7]


#### 4) Perform a scalar multiplication of c with 4

In [ ]:
# Perform a scalar multiplication of c with 4
scalar_c = c*4
scalar_c

array([[ 4,  8, 12, 16],
       [20, 24, 28, 32],
       [36, 40, 44, 48]])

#### 5) Transpose c

In [ ]:
# Transpose c
c_transpose = c.transpose()

#### 6) Reshape c to a 4 x 3 array
What is the difference between the transpose and reshape operations?

The transpose turns the rows of the matrix into columns, while the reshape changes the shape of the array. The latter iterate over the values left-right top-bottom and places it in the shape required.

In [ ]:
# Reshape c to a 4 x 3 array
c_reshape = c.reshape(4,3)

#### 7) Perform an element-wise multiplication of the reshaped c and transposed c

In [ ]:
# Perform an element-wise multiplication of the reshaped c and transposed c
element_wise_mult = c_transpose*c_reshape
element_wise_mult

array([[  1,  10,  27],
       [  8,  30,  60],
       [ 21,  56,  99],
       [ 40,  88, 144]])

### Random
Random number generation plays a crucial role in configuring and evaluating many numerical and machine learning algorithms. Whether it's for randomly initializing weights in a neural network, splitting data into random subsets, or shuffling a dataset, the ability to generate random numbers (specifically repeatable pseudo-random numbers) is vital.

#### 8) Create a half hourly power profile for 1 year filled with random numbers between 0 and 50

In [ ]:
# create a half hourly power profile for 1 year filled with random numbers between 0 and 50
half_hour_profile = np.random.uniform(low = 0.0, high= 50.0, size = (365*48))

#### 9) Reshape the array into daily half hour profiles

In [ ]:
# reshape the array into daily half hour profiles
daily_profile = half_hour_profile.reshape(48,365)

#### 10) convert this array to energy

In [ ]:
# convert to energy
energy_array = (daily_profile*0.5).sum()
print(f'The yearly energy consumption is: {energy_array/1000} MWh')

The yearly energy consumption is: 213.8075 MWh


  
#### Animation and Code Sources  

Numpy GIF: <a href="https://matteding.github.io/images/broadcasting-3d-scalar.gif">Matt Eding</a>  
